---
- name: Install Nagios and check_mk
  hosts: all
  become: true
  tasks:
  
  - name: Test omd status
    command: omd status
    ignore_errors: yes
    become: true
    register: output
  - debug:
      var=output

  - name: Test omd status when site does not exist
    command: omd status fake
    ignore_errors: yes
    become: true
    register: result_fake
  - debug:
      var=result_fake
  
  - name: Create site
    command: omd create test
    when: output is succeeded
    become: true
    
  #- name: Test return code
    #command: omd create test2
   # when: output.rc == 0
    
      
      
    
