---
- name: Install Nagios and check_mk
  hosts: all
  become: true
  tasks:
  
  - name: Test omd status
    command: omd status test
    ignore_errors: yes
    become: true
    register: output
  - debug:
      var=output
      
  - name: Create site
    command: omd create test
    when: output is failed
    become: true
    
 - name: Test return code
   command: omd create test2
   when: output.rc == 0
    
      
      
    
