---
- name: Adding a new user without Args
  hosts: all
  
  tasks:
  
  - name: Install the CORE prereqs
    become: yes
    yum:
      name:
        - gcc
        - glibc
        - glibc-common
        - perl
        - httpd
        - php
        - wget
        - unzip
        - httpd
        - php
        - gd
        - gd-devel
        - perl
        - postfix
   
  - name: Install the Prerequisite packages
    become: yes
    yum:
      name:
        #- gcc
        #- glibc
        #- glibc-common
        #- perl
        #- unzip
        #- wget
        #- httpd
        #- php
        #- gd
        #- gd-devel
        #- perl
        #- postfix
        - gettext
        - autoconf
        - automake
        - make
        - openssl-devel
        - net-snmp
        - net-snmp-utils
        - perl-Net-SNMP
        - ntp
        - libdbi-devel
      state: present
      
  - name: Download the source
    become: yes
    get_url:
      #url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      url: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.5.tar.gz
      dest: /opt/
      
  - name: Unarchive
    unarchive:
    become: yes
      src: /opt/nagioscore-nagios-4.4.5.tar.gz
      dest: /opt/
      remote_src: yes
      
  - name: Compile
    shell: ./configure
    become: yes
    args:
      chdir: /opt/nagioscore-nagios-4.4.5/
      
  - name: Make all
    shell: make all
    become: yes
    args:
      chdir: /opt/nagioscore-nagios-4.4.5/
      
  - name: Create Users and Groups
    shell: make install-groups-users
    become: yes
    args:
      chdir: /opt/nagioscore-nagios-4.4.5/
      
  - name: User Mod
    shell: usermod -a -G nagios apache
    become: yes
    args:
      chdir: /opt/nagioscore-nagios-4.4.5/
      
  - name: make install
    shell: make install
    become: yes
    args:
      chdir: /opt/nagioscore-nagios-4.4.5/
  
  - name: make install daemoninit
    shell: make install-daemoninit
    become: yes
    args:
      chdir: /opt/nagioscore-nagios-4.4.5/
      
  - name: System cty
    shell: systemctl enable httpd.service
    become: yes
    args:
      chdir: /opt/nagioscore-nagios-4.4.5/
      
  - name: Install command mode
    shell: make isntall-commandmode
    become: yes
    args:
      chdir: /opt/nagioscore-nagios-4.4.5/
   
      
  - name: Subscription Manager
    become: yes
    shell: "subscription-manager repos --enable=rhel-7-server-optional-rpms"
      
  - name: Wget dl fedora
    become: yes
    get_url:
      url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      dest: /tmp/
      
  - name: Check if epel latest alrteady installed
    become: yes
    shell: "rpm -qa | grep epel"
    register: output
  - debug:
      var=output
   
  - name: RPM
    shell: rpm -ihv epel-release-latest-7.noarch.rpm
    args:
      chdir: /tmp/
    when: output is failed
      
  - name: Optional Repos
    become: yes
    shell: "subscription-manager repos --enable=rhel-7-server-optional-rpms"
    
    
  - name: 
    
      
  #- name:
    #become: yes
    #shell: rpm -ihv epel-release-latest-7.noarch.rpm
    #args:
      #chdir: /tmp/
