---
- name: Adding a new user without Args
  hosts: all
  
  tasks:
  
  - name: Install the Prerequisite packages
    become: yes
    yum:
      name:
        - gcc
        - glibc
        - glibc-common
        - perl
        - unzip
        - wget
        - httpd
        - php
        - gd
        - gd-devel
        - perl
        - postfix
      state: present

  - name: Download the source
    become: yes
    get_url:
      #url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      url: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.5.tar.gz
      dest: /home/mrh/
      
  - name: Download and Unarchive
    unarchive:
      src: nagioscore-nagios-4.4.5.tar.gz
      dest: /home/mrh/
      
  #- name:
    #become: yes
    #shell: rpm -ihv epel-release-latest-7.noarch.rpm
    #args:
      #chdir: /tmp/
