---
- name: Adding a new user without Args
  hosts: all
  become: true
  #ansible_become: true
  #ansible_become_method: su
  #ansible_become_user: root
  tasks:
  
  - name: Install the CORE prereqs
    yum:
      name:
        - gcc
        - glibc
        - glibc-common
        - wget
        - unzip
        - httpd
        - php
        - gd
        - gd-devel
        - perl
        - postfix 
        #- perl
        #- httpd
        #- php
        #- wget
        #- gd
        #- gd-devel
        #- autoconf
        #- automake
        #- make
        #- openssl-devel
        #- net-snmp
        #- net-snmp-utils
        #- ntp
        #- libdbi-devel
      state: present
    become: true
      
  - name: Download the source
    get_url:
      #url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      url: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.5.tar.gz
      dest: /tmp/
    become: true
    
  - name: Unarchive
    unarchive:
      src: /tmp/nagioscore-nagios-4.4.5.tar.gz
      dest: /tmp/
      remote_src: yes
    become: true
      
  - name: Compile
    shell: ./configure
    args:
      chdir: /tmp/nagioscore-nagios-4.4.5/
    become: true
      
  - name: Make all
    shell: make all
    args:
      chdir: /tmp/nagioscore-nagios-4.4.5/
    become: true
      
  - name: Create Users and Groups
    shell: make install-groups-users
    args:
      chdir: /tmp/nagioscore-nagios-4.4.5/
    become: true
      
  - name: User Mod
    shell: usermod -a -G nagios apache
    args:
      chdir: /tmp/nagioscore-nagios-4.4.5/
    become: true
      
  - name: make install
    shell: make install
    args:
      chdir: /tmp/nagioscore-nagios-4.4.5/
    become: true
  
  - name: make install daemoninit
    shell: make install-daemoninit
    args:
      chdir: /tmp/nagioscore-nagios-4.4.5/
    become: true
      
  - name: System cty
    shell: systemctl enable httpd.service
    args:
      chdir: /tmp/nagioscore-nagios-4.4.5/
    become: true
      
  - name: Install command mode
    shell: make install-commandmode
    args:
      chdir: /tmp/nagioscore-nagios-4.4.5/
    become: true
      
  - name: Make install config
    shell: make install-config
    args:
      chdir: /tmp/nagioscore-nagios-4.4.5/
    become: true
      
  - name: Install command mode
    shell: make install-webconf
    args:
      chdir: /tmp/nagioscore-nagios-4.4.5/
    become: true
      
  - name: Firewall rule changes
    shell: firewall-cmd --zone=public --add-port=80/tcp
    args:
      chdir: /tmp/nagioscore-nagios-4.4.5/
    become: true
      
  - name: Firewall rule changes
    shell: firewall-cmd --zone=public --add-port=80/tcp --permanent
    args:
      chdir: /tmp/nagioscore-nagios-4.4.5/
    become: true
   
  #- name: Create Nagios Admin User Account
    #become: yes
    #shell: |
      #httpd -c /usr/local/nagios/htpasswd.users nagiosadmin
      
      #expect "password:"
      #send "admin"
      
      #expect "password:"
      #send "admin"
    #args:
      #chdir: /opt/nagioscore-nagios-4.4.5/
    
      
  - name: Create Nagios Admin User Account
    shell: sudo htpasswd -bc /usr/local/nagios/htpasswd.users nagiosadmin admin
    args:
      chdir: /tmp/nagioscore-nagios-4.4.5/
      
  - name: Start File Beat
    become: true
    shell: chmod o+r /usr/local/nagios/etc/htpasswd.users
    args:
      chdir: /usr/local/nagios/etc/
      
  #- name: Subscription Manager
    #become: yes
    #shell: "subscription-manager repos --enable=rhel-7-server-optional-rpms"
  
  #####PLUGINS?#####    
  #- name: Wget dl fedora
    #become: yes
    #get_url:
      #url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      #dest: /tmp/
      
  #- name: Check if epel latest alrteady installed
    #become: yes
    #shell: "rpm -qa | grep epel"
    #ignore_errors: yes
    #register: output
  #- debug:
      #var=output
   
  #- name: RPM
    #shell: rpm -ihv epel-release-latest-7.noarch.rpm
    #args:
      #chdir: /tmp/
    #when: output is failed
      
  #- name: Optional Repos
    #become: yes
    #shell: "subscription-manager repos --enable=rhel-7-server-optional-rpms"
    
  - name: Start Apache Webserver
    service:
      name: httpd
      state: started
    become: true
   
  - name: Start Service Daemon
    service:
      name: nagios
      state: started
    become: true
      
  #- name:
    #become: yes
    #shell: rpm -ihv epel-release-latest-7.noarch.rpm
    #args:
      #chdir: /tmp/
